name: Monitor Cursor Updates

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    - name: Build and run monitor
      run: |
        cd cursor/scripts
        go mod tidy
        go run main.go
    
    - name: Commit changes if any
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add cursor/
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update: New Cursor version detected"
        git push